import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/components/authProvider";
import SessionProvider from "@/app/components/sessionProvider";
import QueryProvider from "@/app/components/queryProvider";
import { Toaster } from "@/components/ui/toaster";
import DetailLayout from "./components/detailLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SessionProvider>
            <AuthProvider>
              <DetailLayout children={children} />
              <Toaster />
            </AuthProvider>
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
